version: 2


models:
  - name: tourism_dbt
    description: "Tourism-related data for places"
    meta:
      joins:
        - join: ratings_dbt
          sql_on: ${tourism_dbt.place_id} = ${users_dbt.place_id}
    columns:
      - name: place_id
        description: "Unique id for place"
        tests:
          - unique
      - name: place_name
        description: "Name of the place"
        tests:
          - not_null
      - name: category
        description: "Category of the place"
      - name: city
        description: "City of the place"
      - name: price
        description: "Price to visit this place with tourism"
      - name: rating
        description: "Average rating provided to this place"
        tests:
          - not_null
          # - accepted_values: { values: [1, 2, 3, 4, 5] }
      - name: time_minutes
        description: "Minutes consumed in this place"
      - name: coordinate
        description: "Co-ordinates of this place in a json"
      - name: lat
        description: "Co-ordinates of this place (latitude)"
      - name: long
        description: "Co-ordinates of this place (longitude)"

  - name: packages_dbt
    description: "Information about packages related to places"
    meta:
      joins:
        - join: tourism_dbt
          sql_on: ${tourism_abt.place_name} = ${packages_dbt.Places}
    columns:
      - name: user_id
        description: "Unique id of the user"
        tests:
          - unique
      - name: location
        description: "Location where user resides in"
      - name: age
        description: "Age of the user"
      - name: package_id
        description: "Unique id for the package"
        tests:
          - unique
      - name: package_name
        description: "Name of the package"
        tests:
          - not_null
      - name: place_name
        description: "Name of the place associated with the package"
        tests:
          - not_null
      - name: package_price
        description: "Price of the package"
      - name: duration_days
        description: "Duration of the package in days"

  - name: ratings_dbt
    description: "Ratings provided by users for places"
    meta:
      joins:
        - join: users
          sql_on: ${ratings_dbt.user_id} = ${users_dbt.user_id}
    columns:
      - name: user_id
        description: "User who took packages and their rating"
        meta: 
          dimension:
            label: "user_id"
            description: "unique list of packages"
      - name: place_id
        description: "Unique Id of a place"
        tests:
          - not_null
      - name: place_ratings
        description: "Ratings provided by these users"
        tests:
          - not_null
          # - accepted_values: { values: [1, 2, 3, 4, 5] }

  - name: users_dbt
    description: "Information about users"
    meta:
      joins:
        - join: ratings_dbt
          sql_on: ${ratings_dbt.user_id} = ${users_dbt.user_id}
        - join: tourism_dbt
          sql_on: ${tourism_dbt.place_id} = ${users_dbt.place_id}
    columns:
      - name: user_id
        description: "Unique id of the user"
        tests:
          - unique
      - name: location
        description: "Location where the user resides in"
      - name: age
        description: "Age of the user"
